alias subs='subliminal download -l en'
alias subspl='subliminal download -l pl'
alias toxac36='. .tox/py36/bin/activate'
alias toxac27='. .tox/py27/bin/activate'
alias vim='PYTHONPATH=$(pwd) vim'
alias pudbtest='pudb3 $(which pytest) -s'
alias pudbtest2='pudb $(which pytest) -s'
alias gitdiff='git difftool --dir-diff'
alias dockerclean='docker ps -aq | xargs docker rm'
alias dockercomposeup='docker-compose up --build && docker-compose down -v'
